name: Test project

on: push

jobs:
  test-thermostat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup  Pytest
        run: pip install -r requirements.txt
        
      - name: Run  Pytest
        run: |
          cd tests
          gcc --coverage --shared -fPIC -o deadband.so -I ../src ../src/deadband/deadband.c
          gcc  --shared -fPIC -o gating.so -I test_build_c test_build_c/gating.c
          pytest --md-report --md_report_verbose=1 --md-report-output=ptr.md --md-report-flavor=github test_deadband-ABI-mode.py 
          cat ptr.md >> $GITHUB_STEP_SUMMARY
      - name: report covrage
        run: |    
          echo '```' >> $GITHUB_STEP_SUMMARY
          cd tests
          gcovr -r ../src/deadband . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY