name: Test project

on: push

jobs:
  test-thermostat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup  Pytest
        run: pip install -r requirements.txt
        
      - name: Run  Pytest
        run: |
          cd tests
          gcc --coverage --shared -fPIC -o deadband.so -I ../src ../src/deadband/deadband.c
          gcc  --shared -fPIC -o gating.so -I test_build_c test_build_c/gating.c
          pytest -v --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed test_deadband-ABI-mode.py >> $GITHUB_STEP_SUMMARY
      - name: report covrage
        run: |    
          echo "```" >> $GITHUB_STEP_SUMMARY
          gcovr -r ../src/deadband .
          echo "```" >> $GITHUB_STEP_SUMMARY