name: Test project

on: push

jobs:
  test-thermostat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup  Pytest
        run: pip install -r requirements.txt
        
      - name: Run  Pytest
        run: |
          cd tests
          gcc --coverage --shared -o deadband.so -I ../src ../src/deadband/deadband.c
          pytest test_deadband-ABI-mode.py
          gcovr -r ../src/deadband .